export const PLATFORM_AUDIT_ACTIONS = {
  USER_CREATED: 'USER_CREATED',
  USER_ACTIVATED: 'USER_ACTIVATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  APP_ACCESS_GRANTED: 'APP_ACCESS_GRANTED',
  APP_ACCESS_REVOKED: 'APP_ACCESS_REVOKED',
  APP_ACCESS_ROLE_CHANGED: 'APP_ACCESS_ROLE_CHANGED',
  APP_ACCESS_ENABLED: 'APP_ACCESS_ENABLED',
  APP_ACCESS_DISABLED: 'APP_ACCESS_DISABLED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET: 'PASSWORD_RESET',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
  SESSIONS_REVOKED: 'SESSIONS_REVOKED',
} as const

export type PlatformAuditAction =
  (typeof PLATFORM_AUDIT_ACTIONS)[keyof typeof PLATFORM_AUDIT_ACTIONS]
