export { useProductos, useCreateProducto, useUpdateProducto, useDeleteProducto, useLotes, useCreateLote, productosKeys } from './use-productos'
export { useClientes, useCreateCliente, useUpdateCliente, clientesKeys } from './use-clientes'
export { usePedidos, useCreatePedido, useAprobarPedido, useTomarPedido, useCompletarItemPedido, useCancelarPedido, pedidosKeys } from './use-pedidos'
export { useStockOverview, useStockMovimientos, stockKeys } from './use-stock'
export { useHistorial, historialKeys } from './use-historial'
export { useDashboardOverview, dashboardKeys } from './use-dashboard'
